/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Greeter } from "./Greeter";
export type { MyName } from "./MyName";
export type { Inbox } from "./Inbox";
export type { PeopleStorage } from "./PeopleStorage";
export type { PeopleStorageFactory } from "./PeopleStorageFactory";

export { Greeter__factory } from "./factories/Greeter__factory";
export { MyName__factory } from "./factories/MyName__factory";
export { Inbox__factory } from "./factories/Inbox__factory";
export { PeopleStorage__factory } from "./factories/PeopleStorage__factory";
export { PeopleStorageFactory__factory } from "./factories/PeopleStorageFactory__factory";
