/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export interface PeopleStorageFactoryInterface extends ethers.utils.Interface {
  functions: {
    "addPerson(uint256,string,uint256)": FunctionFragment;
    "createPeopleStorage()": FunctionFragment;
    "getPeopleStorage(uint256)": FunctionFragment;
    "getPeopleStorageCount()": FunctionFragment;
    "getPerson(uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "addPerson",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPeopleStorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPeopleStorage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPeopleStorageCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPerson",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addPerson", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createPeopleStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPeopleStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPeopleStorageCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPerson", data: BytesLike): Result;

  events: {};
}

export interface PeopleStorageFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PeopleStorageFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addPerson(
      _storeIndex: BigNumberish,
      _name: string,
      _age: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createPeopleStorage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getPeopleStorage(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getPeopleStorageCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    getPerson(
      _storageIndex: BigNumberish,
      _personIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber]>;
  };

  addPerson(
    _storeIndex: BigNumberish,
    _name: string,
    _age: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createPeopleStorage(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getPeopleStorage(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getPeopleStorageCount(overrides?: CallOverrides): Promise<BigNumber>;

  getPerson(
    _storageIndex: BigNumberish,
    _personIndex: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber]>;

  callStatic: {
    addPerson(
      _storeIndex: BigNumberish,
      _name: string,
      _age: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createPeopleStorage(overrides?: CallOverrides): Promise<void>;

    getPeopleStorage(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getPeopleStorageCount(overrides?: CallOverrides): Promise<BigNumber>;

    getPerson(
      _storageIndex: BigNumberish,
      _personIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    addPerson(
      _storeIndex: BigNumberish,
      _name: string,
      _age: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createPeopleStorage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getPeopleStorage(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPeopleStorageCount(overrides?: CallOverrides): Promise<BigNumber>;

    getPerson(
      _storageIndex: BigNumberish,
      _personIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addPerson(
      _storeIndex: BigNumberish,
      _name: string,
      _age: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createPeopleStorage(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getPeopleStorage(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPeopleStorageCount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPerson(
      _storageIndex: BigNumberish,
      _personIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
